version: "3.8"

services:

  tomcat:
    build:
      context: .
      args:
        - version=9.0.41
    image: leadstec/tomcat:9.0
    ports:
      - "50521:8080"
    volumes:
      - ~/volumes/tomcat.local/log:/data/log
      - ~/volumes/tomcat.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
      - deploy
    hostname: tomcat.local
    container_name: tomcat.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
  deploy:
    file: ./deploy
