version: "3.7"
# Set -arch=_aarch64 for arm build
# change major to JRE major version, i.e. 8,9
services:
  tomcat:
    build:
      context: .
      args:
#        - arch=_aarch64
        - version=8.5.49
        - build=dev
    image: leadstec/tomcat:8.5.49
    ports:
      - "50521:8080"
    volumes:
      - ~/volumes-data/tomcat.local/log:/data/log
      - ~/volumes-data/tomcat.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
      - deploy
    hostname: tomcat.local
    container_name: tomcat.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
  deploy:
    file: ./deploy
